apiVersion: v2
name       : sellmatica-metrics-api-chart
description: My Helm chart for sellmatica-metrics-api
type       : application
version    : 1.0   # This is the Helm Chart version
appVersion : "1.0" # This is the version of the application being deployed

