apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service_app: metrics-server
  name: metrics-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service_app: metrics-server
  template:
    metadata:
      labels:
        service_app: metrics-server
    spec:
      containers:
        - args:
            - python
            - manage.py
            - metrics-server
            - --host
            - 0.0.0.0
            - --port
            - "6000"
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: API_BASE_URL
                  name: env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
          image: cr.yandex/crp1t6m7uhtcu84orrjq/sellmatica-metrics-app:1.0
          name: metrics-server
      restartPolicy: Always
