apiVersion: v1
kind: Service
metadata:
  labels:
    service: metrics-app
    environment: production
  name: metrics-app-service
spec:
  ports:
    - name: load-balancer
      port: 8000
      targetPort: 80
  selector:
    container: metrics-app
    environment: production
  type: LoadBalancer
  loadBalancerIP: 84.201.174.250
