apiVersion: v1
kind: Service
metadata:
  labels:
    service: metrics-server
    environment: production
  name: metrics-server-service
spec:
  ports:
    - name: metrics-server-service
      port: 6000
      targetPort: 6000
  selector:
    container: metrics-server
    environment: production
  type: ClusterIP