apiVersion: v1
kind: Service
metadata:
  labels:
    service_app: metrics-server
  name: metrics-server-service
spec:
  type: ClusterIP
  ports:
    - name: metrics-server-http
      port: 6000
  selector:
    service_app: metrics-server
  type: ClusterIP