apiVersion: v1
kind: Service
metadata:
  labels:
    service_app: metrics-app
  name: metrics-app-service
spec:
  ports:
    - name: load-balancer
      port: 8000
      targetPort: 80
  selector:
    service_app: metrics-app
  type: LoadBalancer
  loadBalancerIP: 84.201.174.250
