apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    container: metrics-app
    environment: production
  name: metrics-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      container: metrics-app
      environment: production
  template:
    metadata:
      labels:
        container: metrics-app
        environment: production
    spec:
      containers:
        - args:
            - uvicorn
            - src:app
            - --host
            - 0.0.0.0
            - --port
            - "80"
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: API_BASE_URL
                  name: env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: METRICS_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: METRICS_SERVER_HOST
                  name: env
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          name: metrics-app
          ports:
            - containerPort: 80
      restartPolicy: Always
