---
- hosts: "yandex-compute-cloud"
  vars:
    USER: "svc-wsl"

  tasks:
    - name: "Install docker, git via apt"
      become: true
      apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: true
      with_items:
        - docker.io
        - git

    - name: "Install docker-compose plugin"
      become: true
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64" \
        -o /usr/bin/docker-compose 
      args:
        executable: /bin/bash

    - name: "Create docker group and make access"
      become: true
      shell: |
        groupadd -f docker && chown root:docker /var/run/docker.sock \
        && chmod 770 /usr/bin/docker-compose && chown root:docker /usr/bin/docker-compose \
        && usermod -aG docker "{{ USER }}" \
      args:
        executable: /bin/bash

    - name: "Drop SSH keys"
      become: true
      copy:
        src: "/home/{{ USER }}/.ssh/id_rsa"
        dest: "/home/{{ USER }}/.ssh/id_rsa"
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0600"

    - name: "Add Git to known_hosts"
      shell: |
        ssh-keyscan -H github.com >> /home/"{{ USER }}"/.ssh/known_hosts
      args:
        executable: /bin/bash
